server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: qlsdud
    password: qlsdud0604

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 860158119940-8ohdluti1lkm0g331r65vpae2l47r2vr.apps.googleusercontent.com
            client-secret: -eT8Dn4LsYopvGKRwmX1dTY2
            scope:
              - email
              - profile

          facebook:
            client-id: 2914550368855859
            client-secret: b3ccd996dfcec275db6830f974240bf5
            scope:
              - email
              - public_profile

          naver:
            client-id: Sn_nSO71rzegN3V0p4Lz
            client-secret: 18TQAL9Bm1
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize   # 이 주소로 접근 시 네이버 로그인창 제공
            token-uri: https://nid.naver.com/oauth2.0/token   # 이 주소로 접근 시 토큰 발급
            user-info-uri: https://openapi.naver.com/v1/nid/me   # 이 주소로 접근 시 프로필 정보 제공
            user-name-attribute: response   # 회원정보를 json 형태로 받는데 response라는 키 값으로 네이버가 제공

